//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Shared.Resources {
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXA.MSEM.SharedKernel.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorğu üçün ayrılmış müddət bitdi..
        /// </summary>
        public static string AsanSignVerificateAuthenticateExpire {
            get {
                return ResourceManager.GetString("AsanSignVerificateAuthenticateExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat əskikliyinə görə xəta baş verdi..
        /// </summary>
        public static string BindError {
            get {
                return ResourceManager.GetString("BindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birdən çox icraçı ola bilməz.
        /// </summary>
        public static string CannotBeMoreThanOneExecutor {
            get {
                return ResourceManager.GetString("CannotBeMoreThanOneExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyəri, kart nömrəsi formatına uyğun deyil..
        /// </summary>
        public static string CreditCardValidator {
            get {
                return ResourceManager.GetString("CreditCardValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat bazası ilə mübadilə xətası.
        /// </summary>
        public static string DbException {
            get {
                return ResourceManager.GetString("DbException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sənəd növü mərhələləri təyin edilməyib.
        /// </summary>
        public static string DocumentTypeStagesNotDefined {
            get {
                return ResourceManager.GetString("DocumentTypeStagesNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain istifadəçi tapılmadı..
        /// </summary>
        public static string DomainUserNotFound {
            get {
                return ResourceManager.GetString("DomainUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dublikat məlumat əlavə edilə bilməz.
        /// </summary>
        public static string DuplicateDataNotAllowed {
            get {
                return ResourceManager.GetString("DuplicateDataNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təkrarlanan məlumat xətası.
        /// </summary>
        public static string DuplicateKeyException {
            get {
                return ResourceManager.GetString("DuplicateKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Poçt ünvanı təsdiq edilməyib.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyəri, düzgün email formatında deyil..
        /// </summary>
        public static string EmailValidator {
            get {
                return ResourceManager.GetString("EmailValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyəri &apos;{PropertyValue}&apos;  dəyərinə bərabər olmalıdır..
        /// </summary>
        public static string EqualValidator {
            get {
                return ResourceManager.GetString("EqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xəta baş verdi..
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əməliyyat uğursuz oldu.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields məlumatları tapılmadı.
        /// </summary>
        public static string FieldsNotFound {
            get {
                return ResourceManager.GetString("FieldsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faylın məzmunu boşdur..
        /// </summary>
        public static string FileContentIsEmpty {
            get {
                return ResourceManager.GetString("FileContentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faylın tipi düzgün deyildir.
        /// </summary>
        public static string FileExtension {
            get {
                return ResourceManager.GetString("FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fayl tapılmadı..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fayl yadda saxlanılmadı..
        /// </summary>
        public static string FileNotSave {
            get {
                return ResourceManager.GetString("FileNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faylı oxuma zamanı xəta baş verdi..
        /// </summary>
        public static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Key xətası.
        /// </summary>
        public static string ForeignKeyException {
            get {
                return ResourceManager.GetString("ForeignKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyəri &apos;{ComparisonValue}&apos; dəyərindən böyük olmalıdır..
        /// </summary>
        public static string GreaterThanValidator {
            get {
                return ResourceManager.GetString("GreaterThanValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - əlaqəli dəyər yoxdur.
        /// </summary>
        public static string IdNotExists {
            get {
                return ResourceManager.GetString("IdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat düzgün formatda deyil.
        /// </summary>
        public static string IncorrectFormat {
            get {
                return ResourceManager.GetString("IncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sintaksis düzgün deyil.
        /// </summary>
        public static string IncorrectSyntax {
            get {
                return ResourceManager.GetString("IncorrectSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token düzgün formatda deyil.
        /// </summary>
        public static string InvalidAccessToken {
            get {
                return ResourceManager.GetString("InvalidAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token düzgün formatda deyil.
        /// </summary>
        public static string InvalidAsanLoginToken {
            get {
                return ResourceManager.GetString("InvalidAsanLoginToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPT şifrə yanlışdır.
        /// </summary>
        public static string InvalidOTPCode {
            get {
                return ResourceManager.GetString("InvalidOTPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə səhvdir..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Şifrə səhvdir..
        /// </summary>
        public static string InvalidRepeatedPassword
        {
            get
            {
                return ResourceManager.GetString("InvalidRepeatedPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyərinin uzunluğu {MinLength} və {MaxLength} aralığında olmalıdır. Sizin daxil etdiyiniz uzunluq - {TotalLength}..
        /// </summary>
        public static string LengthValidator {
            get {
                return ResourceManager.GetString("LengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyəri &apos;{ComparisonValue}&apos; dəyərindən kiçik olmalıdır..
        /// </summary>
        public static string LessThanValidator {
            get {
                return ResourceManager.GetString("LessThanValidator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyəri &apos;{ComparisonValue}&apos; dəyərindən kiçik olmalıdır..
        /// </summary>
        public static string LettersOnly
        {
            get
            {
                return ResourceManager.GetString("LettersOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Axtarış filtrlərində xəta var..
        /// </summary>
        public static string LoadResultError {
            get {
                return ResourceManager.GetString("LoadResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesab bloklanıb..
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əsas icraçı mütləq seçilməlidir.
        /// </summary>
        public static string MainExecutorMustSelected {
            get {
                return ResourceManager.GetString("MainExecutorMustSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xananın uzunluğu yalnız rəqəmlər və 20 simvola qədər ola bilər.
        /// </summary>
        public static string Max20Digit {
            get {
                return ResourceManager.GetString("Max20Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyərinin uzunluğu maksimum {MaxLength} olmalıdır.Sizin daxil etdiyiniz uzunluq - {TotalLength}..
        /// </summary>
        public static string MaxLengthValidator {
            get {
                return ResourceManager.GetString("MaxLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyərinin uzunluğu minimum {MinLength} olmalıdır.Sizin daxil etdiyiniz uzunluq - {TotalLength}..
        /// </summary>
        public static string MinLengthValidator {
            get {
                return ResourceManager.GetString("MinLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtarış və ya giriş parametri daxil edilməyib.
        /// </summary>
        public static string MissingParameter {
            get {
                return ResourceManager.GetString("MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sütun sayı sorğu tipinə uyğun deyil..
        /// </summary>
        public static string MoreColumnCount {
            get {
                return ResourceManager.GetString("MoreColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu URL-də heç bir məlumat yoxdur..
        /// </summary>
        public static string NoContent {
            get {
                return ResourceManager.GetString("NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu məlumatı silməyə icazəniz yoxdur.
        /// </summary>
        public static string NoDelete {
            get {
                return ResourceManager.GetString("NoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu əməliyyatı aparmaq üçün icazəniz yoxdur..
        /// </summary>
        public static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyəri boş olmamalıdır..
        /// </summary>
        public static string NotEmptyValidator {
            get {
                return ResourceManager.GetString("NotEmptyValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyəri  &apos;{PropertyValue}&apos; dəyərinə bərabər olmalı deyil..
        /// </summary>
        public static string NotEqualValidator {
            get {
                return ResourceManager.GetString("NotEqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL tapılmadı..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} dəyəri boş olmamalıdır..
        /// </summary>
        public static string NotNullValidator {
            get {
                return ResourceManager.GetString("NotNullValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dəyər etibarlı deyil.
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dəyəri boş olmalıdır..
        /// </summary>
        public static string ObjectMustBeNull {
            get {
                return ResourceManager.GetString("ObjectMustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat tapılmadı.
        /// </summary>
        public static string ObjectNotFound {
            get {
                return ResourceManager.GetString("ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əməliyyat imtina edilmişdir.
        /// </summary>
        public static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təkrar şifrə istifadə edilə bilməz..
        /// </summary>
        public static string PasswordIsUsed {
            get {
                return ResourceManager.GetString("PasswordIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrədə ən azı bir rəqəm olmalıdır (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrədə ən azı bir kiçik hərf (&apos;a&apos;-&apos;z&apos;) olmalıdır..
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrədə ən azı bir simvol olmalıdır..
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parollar ən azı {0} fərqli simvoldan istifadə etməlidir..
        /// </summary>
        public static string PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrədə ən azı bir böyük hərf olmalıdır (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə ən azı {0} simvoldan ibarət olmalıdır..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu əməliyyatı aparmaq üçün icazəniz yoxdur..
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu əməliyyatı icra etmək hüququnuz yoxdur..
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil nömrə təsdiq edilməyib.
        /// </summary>
        public static string PhoneNumberNotConfirmed {
            get {
                return ResourceManager.GetString("PhoneNumberNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu ad artıq mövcutdur .
        /// </summary>
        public static string PropertyAlreadyExists {
            get {
                return ResourceManager.GetString("PropertyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xananın dəyəri boş ola bilməz.
        /// </summary>
        public static string PropertyIsNull {
            get {
                return ResourceManager.GetString("PropertyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referfence Constraint xətası.
        /// </summary>
        public static string ReferfenceConstraintException {
            get {
                return ResourceManager.GetString("ReferfenceConstraintException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh tokenin müddəti bitib. Sistemə yenidən daxil olun.
        /// </summary>
        public static string RefreshTokenExpired {
            get {
                return ResourceManager.GetString("RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token ləğv edilib.
        /// </summary>
        public static string RefreshTokenIsRevoked {
            get {
                return ResourceManager.GetString("RefreshTokenIsRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token artıq istifadə edilib.
        /// </summary>
        public static string RefreshTokenIsUsed {
            get {
                return ResourceManager.GetString("RefreshTokenIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token tapılmadı.
        /// </summary>
        public static string RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("RefreshTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu xana məcburidir.
        /// </summary>
        public static string RequiredAttribute {
            get {
                return ResourceManager.GetString("RequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəni dəyişməyiniz tələb olunur..
        /// </summary>
        public static string RequireResetPassword {
            get {
                return ResourceManager.GetString("RequireResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolun sıfırlanması tələb olunmur.
        /// </summary>
        public static string ResetPasswordDoesNotRequired {
            get {
                return ResourceManager.GetString("ResetPasswordDoesNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu sətr artıq mövcutdur.
        /// </summary>
        public static string RowAlreadyExists {
            get {
                return ResourceManager.GetString("RowAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uğurla yerinə yetirildi..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA aktivləşdirilməyib..
        /// </summary>
        public static string TwoFactorAuthenticationNotEnabled {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessiya vaxtı bitib. Sistemə yenidən daxil olun..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unikal məlumat xətası.
        /// </summary>
        public static string UniqeKeyException {
            get {
                return ResourceManager.GetString("UniqeKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu istifadəçi artıq qeydiyyatdan keçib..
        /// </summary>
        public static string UserAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("UserAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmza sertifikati düzgün deyil..
        /// </summary>
        public static string UserCertificateIsInvalid {
            get {
                return ResourceManager.GetString("UserCertificateIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi tapılmadı..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoxlama xətası baş verdi..
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
